[project]
name = "agent1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bhargav", email = "bhargavbala56@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
]

[project.scripts]
agent1 = "agent1:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
